---
- name: Pull and Run docker image
  hosts: all
  tasks:
    - name: pull images specifed in docker-compose
      command: docker-compose pull
#        shell: docker-compose pull
#        args:
#          chdir: ./..
#        become: True # because you're using sudo
#    - name: pull images specifed in docker-compose
#      ansible.builtin.shell:
#        cmd: docker-compose pull
#    - name: run the pulled docker image in detached mode
#      ansible.builtin.shell:
#        cmd: docker-compose up -d