---
- name: Pull and Run docker image
  hosts: all
  tasks:
    - name: pull images specifed in docker-compose
      ansible.builtin.shell:
        cmd: docker-compose pull
    - name: run the pulled docker image in detached mode
      ansible.builtin.shell:
        cmd: docker-compose up -d